apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server
  labels:
    app: sample-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-server
  template:
    metadata:
      labels:
        app: sample-server
    spec:
      containers:
        - name: sample-server
          image: loggingregistry.azurecr.io/server:v1.1
          ports:
            - containerPort: 80
              name: webinterface
---
apiVersion: v1
kind: Service
metadata:
  name: sample-server
  labels:
    app: sample-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: webinterface
      targetPort: 80
  selector:
    app: sample-server
---

